App\Entity\Produit: 
  nom:
        - NotNull: ~
        - NotBlank: ~
        - Type:
                  type: string
                  message: The value {{ value }} is not a valid {{ type }}.
        - Length:
                  min: 2
                  max: 100
                  minMessage: "field: nom must be at least {{ limit }} characters long"
                  maxMessage: "field: nom  cannot be longer than {{ limit }} characters"
  poids: 
        - NotNull: ~
        - NotBlank: ~
        - Type:
                  type: string
                  message: The value {{ value }} is not a valid {{ type }}.
        - Length:
                  min: 2
                  max: 100
                  minMessage: "field: nom must be at least {{ limit }} characters long"
                  maxMessage: "field: nom  cannot be longer than {{ limit }} characters"
  prix:
        - NotNull: ~
        - NotBlank: ~
        - Type:
                  type: float
                  message: The value {{ value }} is not a valid {{ type }}.  
  photo:
        - NotNull: ~
        - NotBlank: ~
        - Type:
                  type: string
                  message: The value {{ value }} is not a valid {{ type }}.
        - Length:
                  max: 255
                  maxMessage: "field: photo must be at most {{ limit }} characters long"
  description:
            - NotNull: ~
            - NotBlank: ~
            - Type:
                  type: string
                  message: The value {{ value }} is not a valid {{ type }}.
            - Length:
                  min: 2
                  minMessage: "field: description must be at least {{ limit }} characters long"
  stock:
        - NotNull: ~
        - NotBlank: ~
        - Type:
                type: integer
                message: The value {{ value }} is not a valid {{ type }}.
  date_creation:
        - Type:
                type: \DateTimeInterface
                message: The value {{ value }} is not a valid {{ type }}.

App\Entity\Panier: 
  quantite:
        - NotNull: ~
        - NotBlank: ~
        - Type:
                type: integer
                message: The value {{ value }} is not a valid {{ type }}.

App\Entity\Categorie: 
  name:
        - NotNull: ~
        - NotBlank: ~
        - Type:
                  type: string
                  message: The value {{ value }} is not a valid {{ type }}.
        - Length:
                  min: 2
                  max: 100
                  minMessage: "field: nom must be at least {{ limit }} characters long"
                  maxMessage: "field: nom  cannot be longer than {{ limit }} characters"

App\Entity\Commande: 
  adresse_livraison:
        - NotNull: ~
        - NotBlank: ~
        - Type:
                  type: string
                  message: The value {{ value }} is not a valid {{ type }}.
        - Length:
                  min: 1
                  max: 255
                  minMessage: "field: nom must be at least {{ limit }} characters long"
                  maxMessage: "field: nom  cannot be longer than {{ limit }} characters"
  code_postal:
        - NotNull: ~
        - NotBlank: ~
        - Type:
                type: integer
                message: The value {{ value }} is not a valid {{ type }}.
        - Length:
                  min: 5
                  max: 5
                  minMessage: "field: nom must be at least {{ limit }} characters long"
                  maxMessage: "field: nom  cannot be longer than {{ limit }} characters"
  ville:
        - NotNull: ~
        - NotBlank: ~
        - Type:
                  type: string
                  message: The value {{ value }} is not a valid {{ type }}.
        - Length:
                  min: 1
                  max: 255
                  minMessage: "field: nom must be at least {{ limit }} characters long"
                  maxMessage: "field: nom  cannot be longer than {{ limit }} characters"
  complement_adresse:
        - NotBlank: ~
        - Type:
                  type: string
                  message: The value {{ value }} is not a valid {{ type }}.
  prix:
        - NotNull: ~
        - NotBlank: ~
        - Type:
                  type: float
                  message: The value {{ value }} is not a valid {{ type }}. 
  paiement_status: 
        - NotNull: ~
        - NotBlank: ~
        - Type:
                  type: boolean

App\Entity\User: 
  properties: 
      email: 
         - NotNull: ~
         - NotBlank: ~
         - Type: 
                  type: string
                  message: The value {{ value }} is not a valid {{ type }}
         - Length: 
                  min: 3
                  max: 50
                  minMessage: "field email must be at least {{ limit }} characters long"
                  maxMessage: "field email cannot be longer than {{ limit }} characters"



        
