# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

# environnement
    #app_param_env: "%env(APP_ENV)%"



#-------------------------------------------------------------------------
# Id de la balise body pour chaque page du site

    HOME_PAGE: "home"
    LOGIN: "login"
    LEGAL_PAGE: "mentions"
    COOKIE_PAGE: "cookie"
    HORAIRES_PAGE: "horaires"
    BISCUITS_PAGE: "biscuits"
    CHOCOLATS_PAGE: "chocolats"
    FRIANDISES_PAGE: "friandises"
    PRESENTATION_PAGE: "presentation"
    CONDITIONS_PAGE: "conditions"
    PRODUCT_PAGE: "produits"
    NOUS_CONTACTER_PAGE: "nous_contacter"
    ORDER_CONFIRMATION: "confirmation-commande"


#--------------------------------------------------------------------------
services:
    # default configuration for services in *this* file
    # autowire: autocablage
    # l'injection de dépendances de service au niveau du constructeur crée une variable contenant un objet
    # qui devient global à toutes les méthodes de la classe grace à la techno de l'auto-cablage
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
